# THIS SCRIPT IS FOR THE PEOPLE WHO WANT TO BUILD THE L# COMPILER FROM SOURCE.
# THERE ARE MULTIPLE WAYS TO DO THIS. THERE IS USING GIT MANUALLY BY
# CLONING THE REPOSITORY WITH git clone https://github.com/Donkasem55/L-sharp.git
# AND THEN CD-ING INTO THE REPOSITORY, cd L-sharp
# FINALLY, YOU RUN THIS SCRIPT, .\make.ps1, TO BUILD IT. MAKE SURE YOU HAVE PYTHON INSTALLED.

# YOU CAN ALSO USE A PACKAGE MANAGER IF ONE SUPPORTS THIS.

python -m PyInstaller main.py --add-data "stdlib;stdlib" --onefile --name lshrp.exe
